---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
before_install: gem install bundler -v 1.17.2
gemfile:
  - gemfiles/rails_4.2_stable.gemfile
  - gemfiles/rails_5.0_stable.gemfile
  - gemfiles/rails_5.1_stable.gemfile
  - gemfiles/rails_5.2_stable.gemfile
script: bundle exec rspec
